### PR TITLE
Manage Session Cookies

### PR DESCRIPTION
**Pull request by tomykho**

### CODE REVIEW

**Comment by jeromegamez** [comment]
As said on the SDK's repo: this is looking very promising, thanks for taking the time to implement this! I'll try to get to it shortly! 🤞

**Comment by jeromegamez** [comment]
Unfortunately this will take longer than I thought - somehow the added URL in the HttpKeyStore breaks stuff, and I have to figure out how to integrate the session verifier without making the lib (and subsequently the SDK) even messier than it already is 😅

Out of interest - are you using the tokens library as a standalone lib or in context of the SDK?

**Comment by tomykho** [comment]
> Unfortunately this will take longer than I thought - somehow the added URL in the HttpKeyStore breaks stuff, and I have to figure out how to integrate the session verifier without making the lib (and subsequently the SDK) even messier than it already is 
> 
> Out of interest - are you using the tokens library as a standalone lib or in context of the SDK?

I am using tokens library with https://github.com/kreait/firebase-php

**Comment by jeromegamez** [comment]
Superseded by https://github.com/kreait/firebase-tokens-php/pull/42, since you created the initial implementation with this PR, I added you as a co-author on https://github.com/kreait/firebase-tokens-php/commit/1ea0e3dc48a73202e050bb08a5a602e41dfd31b8, I hope that's alright for you 🤗

**Pull request closed without merging**
